// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package globalsearch.actions;

import java.util.ArrayList;
import java.util.List;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.Term;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import communitycommons.ORM;
import globalsearch.supportfunctions.DirectoryCreator;
import globalsearch.supportfunctions.QueryHelper;

public class BatchDeleteIndexes extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ObjectType;

	public BatchDeleteIndexes(IContext context, java.lang.String ObjectType)
	{
		super(context);
		this.ObjectType = ObjectType;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		String directory = DirectoryCreator.getDirectory();
		// Instantiate the index writer.
		IndexWriter writer = DirectoryCreator.createWriter(directory);
		long deletedSucces = writer.deleteDocuments(QueryHelper.getQuery("EntityName: " + ObjectType, globalsearch.proxies.Enum_SearchType.Advanced));
		if(deletedSucces == -1) {
			return false;
		}
		else {
			writer.commit();
			return true;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "BatchDeleteIndexes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
