// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package globalsearch.actions;

import java.io.File;
import java.io.IOException;
import org.apache.commons.io.FileUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import globalsearch.supportfunctions.DirectoryCreator;

/**
 * Use this to completely remove the index folder and start from scratch.
 */
public class ClearIndexFolder extends CustomJavaAction<java.lang.Boolean>
{
	public ClearIndexFolder(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		String directory = DirectoryCreator.getDirectory();
		File folder = new File(directory);
		deleteFolder(folder);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ClearIndexFolder";
	}

	// BEGIN EXTRA CODE
	public static void deleteFolder(File folder) throws IOException {
	    File[] files = folder.listFiles();
	    if(files!=null) {
	        for(File f: files) {
	            if(f.isDirectory()) {
	                deleteFolder(f);
	            } else {
	            	f.delete();
	            }
	        }
	    }
	    folder.delete();
	}
	// END EXTRA CODE
}
