// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package globalsearch.actions;

import org.apache.lucene.document.Document;
import org.apache.lucene.facet.FacetsConfig;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.Term;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import communitycommons.ORM;
import globalsearch.supportfunctions.DirectoryCreator;
import globalsearch.supportfunctions.IndexHelper;

public class IndexObject extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject ObjectToIndex;
	private java.lang.Boolean UseAdvancedIndexing;
	private java.lang.String JSONBody;
	private java.util.List<IMendixObject> __Facets;
	private java.util.List<globalsearch.proxies.Facet> Facets;

	public IndexObject(IContext context, IMendixObject ObjectToIndex, java.lang.Boolean UseAdvancedIndexing, java.lang.String JSONBody, java.util.List<IMendixObject> Facets)
	{
		super(context);
		this.ObjectToIndex = ObjectToIndex;
		this.UseAdvancedIndexing = UseAdvancedIndexing;
		this.JSONBody = JSONBody;
		this.__Facets = Facets;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Facets = new java.util.ArrayList<globalsearch.proxies.Facet>();
		if (__Facets != null)
			for (IMendixObject __FacetsElement : __Facets)
				this.Facets.add(globalsearch.proxies.Facet.initialize(getContext(), __FacetsElement));

		// BEGIN USER CODE
		if(UseAdvancedIndexing == null) return false;
		if(UseAdvancedIndexing && (JSONBody.isBlank() || JSONBody.isEmpty() || JSONBody == null)) return false;
		if(ObjectToIndex == null) return false;
		
		ILogNode LOG = Core.getLogger("GlobalSearch");
		String directory = DirectoryCreator.getDirectory();
		// Instantiate the index writer.
		IndexWriter writer = DirectoryCreator.createWriter(directory);
		// Delete index if it already existed.
		String GUID = ORM.getGUID(ObjectToIndex).toString();
		writer.deleteDocuments(new Term("id", GUID));
		writer.commit();
		boolean success = true;
		try {
			success = createIndex(LOG, GUID, writer);
		}catch(Exception e) {
			success = false;
		}
		return success;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IndexObject";
	}

	// BEGIN EXTRA CODE
	private boolean createIndex(ILogNode LOG, String GUID, IndexWriter writer) throws Exception {

		LOG.debug("Indexing object with id: " + GUID);
		FacetsConfig config = new FacetsConfig();
		// Create document.
		Document luceneDocument = null;
				
		if(!UseAdvancedIndexing) luceneDocument = IndexHelper.createBasic(ObjectToIndex, this.getContext(), config, Facets);
		else luceneDocument = IndexHelper.createAdvanced(ObjectToIndex, this.getContext(), config, Facets, JSONBody);
		// Add the created document to the index.
		if (luceneDocument != null) {
			writer.addDocument((config.build(luceneDocument)));
		}
		// Returns a number other than -1 if the index has been properly processed.
		long writerSuccessful = writer.commit();
		writer.forceMerge(1);
		if(writerSuccessful != -1) LOG.debug("Finished indexing object with id: " + GUID);
		else LOG.debug("Failed to index object with id: " + GUID);
		
		return writerSuccessful != -1;
	}
	// END EXTRA CODE
}
