// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package globalsearch.actions;

import java.util.List;
import java.util.Map.Entry;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class IndexByEntityName extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String EntityName;
	private java.lang.String IndexMicroflow;

	public IndexByEntityName(IContext context, java.lang.String EntityName, java.lang.String IndexMicroflow)
	{
		super(context);
		this.EntityName = EntityName;
		this.IndexMicroflow = IndexMicroflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> objectListToProcess = Core.retrieveXPathQuery(this.getContext(), "//" + EntityName);
		String paramName = "";
		for(Entry<String,IDataType> entry : Core.getInputParameters(IndexMicroflow).entrySet()) {
			String inputParameterName = entry.getKey();
			paramName = inputParameterName;
			break;
		}
		for(IMendixObject i : objectListToProcess) {
			Core.microflowCall(IndexMicroflow).withParam(paramName, i).execute(getContext());
		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IndexByEntityName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
